### ISSUE TITLE
English monolingual corpus

### ISSUE THREAD

**Issue by sharad461** [amitness/ml-datasets#1]
Hi @amitness, 

Do you happen to know if there is a good English-language corpus with content mostly about Nepal (for example, from English-language newspapers and magazines in Nepal)? I'd scrape the newspapers, but I was wondering if somebody has already done that.

**Comment by amitness** [comment]
I'm not familiar with any project which has done that. You will probably need to scrap the newspapers. Maybe this will be helpful: [nepali-news-crawler](https://github.com/vksbhandary/nepali-news-crawler)

If you do fetch the data, feel free to add that to this repo for future users.
